# Generated by Django 5.0.6 on 2024-07-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0009_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='mobile_store.address'),
        ),
        migrations.AlterField(
            model_name='cart_orders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mobile_store.cart'),
        ),
    ]
